# Generated by Django 5.2.6 on 2025-09-17 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('email_for_orders', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excursion_id', models.IntegerField()),
                ('excursion_title', models.CharField(blank=True, max_length=255)),
                ('hotel_id', models.IntegerField(blank=True, null=True)),
                ('hotel_name', models.CharField(blank=True, max_length=255)),
                ('region_name', models.CharField(blank=True, max_length=120)),
                ('pickup_point_id', models.IntegerField(blank=True, null=True)),
                ('pickup_point_name', models.CharField(blank=True, max_length=255)),
                ('pickup_time_str', models.CharField(blank=True, max_length=16)),
                ('date', models.DateField()),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('infants', models.PositiveIntegerField(default=0)),
                ('gross_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('HOLD', 'HOLD'), ('PAID', 'PAID'), ('CANCELLED', 'CANCELLED'), ('EXPIRED', 'EXPIRED')], default='PENDING', max_length=10)),
                ('payment_method', models.CharField(blank=True, max_length=30)),
                ('booking_code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.company')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Номер брони/заявки')),
                ('hotel_id', models.IntegerField()),
                ('hotel_name', models.CharField(blank=True, max_length=255)),
                ('region_name', models.CharField(blank=True, max_length=120)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-arrival_date', 'hotel_name'],
                'indexes': [models.Index(fields=['hotel_id', 'arrival_date'], name='sales_famil_hotel_i_acd37c_idx'), models.Index(fields=['ref_code'], name='sales_famil_ref_cod_0c375c_idx')],
            },
        ),
        migrations.CreateModel(
            name='GuideProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companies', models.ManyToManyField(blank=True, to='sales.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(blank=True, max_length=64)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('nationality', models.CharField(blank=True, max_length=64)),
                ('passport', models.CharField(blank=True, max_length=64)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelers', to='sales.familybooking')),
            ],
            options={
                'indexes': [models.Index(fields=['last_name', 'first_name', 'dob'], name='sales_trave_last_na_491569_idx')],
            },
        ),
    ]
