# Generated by Django 5.2.6 on 2025-09-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='traveler',
            unique_together={('family', 'last_name', 'first_name', 'dob')},
        ),
        migrations.AddIndex(
            model_name='traveler',
            index=models.Index(fields=['family', 'last_name', 'first_name', 'dob'], name='sales_trave_family__d29180_idx'),
        ),
    ]
