# Generated by Django 5.2.6 on 2025-09-20 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_traveler_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsale',
            name='excursion_language',
            field=models.CharField(blank=True, choices=[('ru', 'Русский'), ('en', 'English'), ('es', 'Español'), ('de', 'Deutsch')], max_length=5),
        ),
        migrations.AddField(
            model_name='bookingsale',
            name='price_per_adult',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bookingsale',
            name='price_per_child',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bookingsale',
            name='price_source',
            field=models.CharField(choices=[('PICKUP', 'По данным pickup/v2'), ('REGION', 'По региональным ценам'), ('MANUAL', 'Указано вручную')], default='PICKUP', max_length=10),
        ),
        migrations.AddField(
            model_name='bookingsale',
            name='room_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='bookingsale',
            index=models.Index(fields=['company', 'date'], name='sales_booki_company_2034b2_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingsale',
            index=models.Index(fields=['excursion_id', 'date'], name='sales_booki_excursi_3937d3_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingsale',
            index=models.Index(fields=['excursion_language'], name='sales_booki_excursi_66da1d_idx'),
        ),
    ]
