# Generated by Django 5.2.6 on 2025-09-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_bookingsale_excursion_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsale',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bookingsale',
            name='pickup_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='bookingsale',
            name='pickup_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
