# Generated by Django 5.2.6 on 2025-09-20 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_bookingsale_pickup_address_bookingsale_pickup_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsale',
            name='batch_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='bookingsale',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='sales.familybooking'),
        ),
        migrations.AddField(
            model_name='bookingsale',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingsale',
            name='sent_to_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='bookingsale',
            name='travelers_csv',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookingsale',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PENDING', 'PENDING'), ('HOLD', 'HOLD'), ('PAID', 'PAID'), ('CANCELLED', 'CANCELLED'), ('EXPIRED', 'EXPIRED')], default='PENDING', max_length=10),
        ),
    ]
