# Generated by Django 5.2.6 on 2025-09-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_bookingsale_batch_code_bookingsale_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='doc_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traveler',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('passport', 'Passport'), ('dni', 'DNI')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='traveler',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
