# Generated by Django 5.2.6 on 2025-09-27 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_inboundemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundemail',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.bookingsale'),
        ),
    ]
