# Generated by Django 5.2.6 on 2025-09-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_inboundemail_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsale',
            name='excursion_language',
            field=models.CharField(blank=True, choices=[('ru', 'Русский'), ('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('de', 'Deutsch')], max_length=5),
        ),
    ]
