# Generated by Django 5.2.6 on 2025-10-04 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_bookingsale_excursion_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledBookingSale',
            fields=[
            ],
            options={
                'verbose_name': 'Cancelled booking',
                'verbose_name_plural': 'Cancelled bookings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sales.bookingsale',),
        ),
        migrations.AddField(
            model_name='bookingsale',
            name='cancel_reason',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='bookingsale',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingsale',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PENDING', 'PENDING'), ('HOLD', 'HOLD'), ('PAID', 'PAID'), ('CANCELLED', 'CANCELLED'), ('EXPIRED', 'EXPIRED')], db_index=True, default='DRAFT', max_length=10),
        ),
        migrations.AddIndex(
            model_name='bookingsale',
            index=models.Index(fields=['status'], name='sales_booki_status_b19193_idx'),
        ),
    ]
