# Generated by Django 5.2.6 on 2025-10-04 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_cancelledbookingsale_bookingsale_cancel_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcursionNetPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excursion_id', models.IntegerField(db_index=True)),
                ('region_slug', models.CharField(blank=True, default='', help_text='Например: malaga, cds, marbella. Можно оставить пустым.', max_length=64)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('net_per_adult', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_per_child', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('child_discount_pct', models.DecimalField(decimal_places=2, default=25, max_digits=5)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, help_text='Если пусто — действует для всех компаний', null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.company')),
            ],
            options={
                'verbose_name': 'Нетто цена экскурсии',
                'verbose_name_plural': 'Нетто цены экскурсий',
                'indexes': [models.Index(fields=['excursion_id', 'region_slug'], name='sales_excur_excursi_9d89e1_idx')],
            },
        ),
    ]
