# Generated by Django 5.2.6 on 2025-10-04 21:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_excursionnetprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excursionnetprice',
            options={'ordering': ['excursion_id', 'region_slug']},
        ),
        migrations.RemoveIndex(
            model_name='excursionnetprice',
            name='sales_excur_excursi_9d89e1_idx',
        ),
        migrations.AddField(
            model_name='excursionnetprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excursionnetprice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='excursionnetprice',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Если пусто — цена действует для всех компаний', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='net_prices', to='sales.company'),
        ),
        migrations.AlterField(
            model_name='excursionnetprice',
            name='net_per_adult',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='excursionnetprice',
            name='region_slug',
            field=models.SlugField(blank=True, help_text='Например: malaga, cds, marbella, estepona', max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='excursionnetprice',
            unique_together={('company', 'excursion_id', 'region_slug')},
        ),
    ]
