# Generated by Django 4.2.25 on 2025-10-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_alter_excursionnetprice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsale',
            name='travelers_names',
            field=models.TextField(blank=True, help_text='Снапшот ФИО через \\n', null=True),
        ),
    ]
